//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltraDynamo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AccelerometerAxisVehicleFront {
            get {
                return ((int)(this["AccelerometerAxisVehicleFront"]));
            }
            set {
                this["AccelerometerAxisVehicleFront"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public decimal SpeedometerVMax {
            get {
                return ((decimal)(this["SpeedometerVMax"]));
            }
            set {
                this["SpeedometerVMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpeedometerUnits {
            get {
                return ((int)(this["SpeedometerUnits"]));
            }
            set {
                this["SpeedometerUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public uint AccelerometerDefaultUpdateInterval {
            get {
                return ((uint)(this["AccelerometerDefaultUpdateInterval"]));
            }
            set {
                this["AccelerometerDefaultUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public uint GyrometerDefaultUpdateInterval {
            get {
                return ((uint)(this["GyrometerDefaultUpdateInterval"]));
            }
            set {
                this["GyrometerDefaultUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public uint InclinometerDefaultUpdateInterval {
            get {
                return ((uint)(this["InclinometerDefaultUpdateInterval"]));
            }
            set {
                this["InclinometerDefaultUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public uint GeolocationDefaultUpdateInterval {
            get {
                return ((uint)(this["GeolocationDefaultUpdateInterval"]));
            }
            set {
                this["GeolocationDefaultUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public uint LightSensorDefaultUpdateInterval {
            get {
                return ((uint)(this["LightSensorDefaultUpdateInterval"]));
            }
            set {
                this["LightSensorDefaultUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public uint CompassDefaultUpdateInterval {
            get {
                return ((uint)(this["CompassDefaultUpdateInterval"]));
            }
            set {
                this["CompassDefaultUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public decimal VehicleWeightKg {
            get {
                return ((decimal)(this["VehicleWeightKg"]));
            }
            set {
                this["VehicleWeightKg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int HorsepowerMax {
            get {
                return ((int)(this["HorsepowerMax"]));
            }
            set {
                this["HorsepowerMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideContentNotice {
            get {
                return ((bool)(this["HideContentNotice"]));
            }
            set {
                this["HideContentNotice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AcceptContentNotice {
            get {
                return ((bool)(this["AcceptContentNotice"]));
            }
            set {
                this["AcceptContentNotice"] = value;
            }
        }
    }
}
